version: "3.9"

services:
  db:
    image: postgres:15.2
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - ./var/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: etc/python/Dockerfile
    container_name: django-app
    volumes:
      - ./django_deploy_project:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "80:80"
    depends_on:
      - web

