# Generated by Django 5.2.3 on 2025-06-12 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0002_person_remove_contractor_contact_person_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='phone',
        ),
    ]
