# Generated by Django 5.2.3 on 2025-06-13 13:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0003_remove_contractor_email_remove_contractor_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seriality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('quantities', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='contractor',
            name='serialities',
            field=models.ManyToManyField(blank=True, related_name='contractors', to='contractors.seriality'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='work_types',
            field=models.ManyToManyField(blank=True, related_name='contractors', to='contractors.worktype'),
        ),
    ]
